In [3]:
import numpy as np

a = np.array([[1,2,3,4], [1,3,5,6]])
print(a)
print(a.ndim)

[[1 2 3 4]
 [1 3 5 6]]
2


In [6]:
a2 = np.array([[[1,3,4,5], [1,2,3,4]]])
print(a2)
print(a2.ndim)

[[[1 3 4 5]
  [1 2 3 4]]]
3


In [8]:
a3 = np.array([1,2,3,4], ndmin=10)
print(a3)
print(a3.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [2]:
print("hello world")

hello world


zeros

In [3]:
import numpy as np
ar_zer = np.zeros(4)
print(ar_zer)

[0. 0. 0. 0.]


ones


In [5]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [7]:
# range fuctions

In [9]:
ar_ran = np.arange(6)
print(ar_ran)

[0 1 2 3 4 5]


In [10]:
# diagonal fuction

In [14]:
ar_dia = np.eye(3,4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [16]:
import numpy as np

var = np.random.rand(5)
print(var)

[0.64030749 0.56525315 0.05594919 0.44327013 0.12320298]


In [18]:
# for randn

var1 = np.random.randn(4)
print(var1)

[-0.70877287  0.71914415 -1.0796618  -0.05128967]


In [20]:
# for ranf

var2 = np.random.ranf(6)
print(var2)

[0.48067032 0.96379712 0.2097965  0.37415154 0.70237387 0.4742782 ]


In [42]:
# for randint
import numpy as np
var3 = np.random.randint(3,10, 4)
print(var3)

[9 5 9 3]


In [2]:
import numpy as np

var = np.array([1,2,3,4])
print(var)
print(var.dtype)

[1 2 3 4]
int64


In [4]:
var1 = np.array([1.0, 2.0, 4.5, 6.0])
print(var1)
print(var1.dtype)

[1.  2.  4.5 6. ]
float64


In [6]:
var2 = np.array(["a", "b", "c", "d"])
print(var2)
print(var2.dtype)

['a' 'b' 'c' 'd']
<U1


In [13]:
var4 = np.array([2,4,5,6,7], dtype= np.int16)
print(var4)
print(var4.dtype)

[2 4 5 6 7]
int16


In [18]:
var5 = np.array([1,3,5,6,7],dtype = "f")
print(var5)
print(var5.dtype)

[1. 3. 5. 6. 7.]
float32


In [21]:
import numpy as np

# arithmetic operations
var1 = np.array([1,2,3,4,5])
varadd = var1 + 3
print(var1)
print(varadd)


[1 2 3 4 5]
[4 5 6 7 8]


In [23]:
var2 = np.array([1,2,3,4,5])
varadd = var2 * 4
print(varadd)

[ 4  8 12 16 20]


In [24]:
var3 = np.array([2,4,6,8,10])
varadd = var3 / 2
print(varadd)

[1. 2. 3. 4. 5.]


In [26]:
var4 = np.array([1,2,3,4,5])
var5 = np.array([1,2,3,4,5])
varadd = var4 * var5
print(varadd)

[ 1  4  9 16 25]


In [31]:
var6 = np.array([[1,2,3,4,5],[1,3,5,7,9]])
var7 = np.array([[1,2,3,4,5], [1,3,5,7,9]])
vardd = np.add(var6, var7)
print(varadd)

[ 1  4  9 16 25]


In [5]:
import numpy as np

# shpae in numpy

var = np.array([[1,2,3], [1,2,3]])
print(var.shape)

(2, 3)


In [6]:
var1 = np.array([[1,2,3,4,5,6,7,8,9], [1,2,3,4,5,6,7,8,9]])
print(var1)
print(var1.ndim)
print(type(var1))
print(var1.shape)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
2
<class 'numpy.ndarray'>
(2, 9)


In [9]:
var4 = np.array([1,2,3,4], ndmin = 5)
print(var4)
print(var4.ndim)
print(var4.shape)

[[[[[1 2 3 4]]]]]
5
(1, 1, 1, 1, 4)


In [12]:
# reshape in numpy array

var5 = np.array([1,3,5,7,9,11])
x = var5.reshape(2,3)
print(var5)
print()
print(var5.ndim)
print()
print(x)
print(x.ndim)

[ 1  3  5  7  9 11]

1

[[ 1  3  5]
 [ 7  9 11]]
2


In [17]:
# convert
var6 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x = var6.reshape(3,4)
one = x.reshape(-1)
print(var6)
print()
print(var6.ndim)
print()
print(x)
print()
print(x.ndim)
print()
print(one)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

1

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
# broadcasting in numpy
var1 = np.array([[1], [2], [3]])
print(var1)
print(var1.shape)
print(var1.ndim)

var2 = np.array([1,2,3])
print(var2)
print("\n")
print(var2.shape)
print(var1 + var2)

[[1]
 [2]
 [3]]
(3, 1)
2
[1 2 3]


(3,)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [2]:
import numpy as np

var = np.array([[1], [2], [3]])
print(var)

var1 = np.array([[1,2],[1,2],[1,2]])
print(var1.shape)

varadd = var + var1
print(varadd)

[[1]
 [2]
 [3]]
(3, 2)
[[2 3]
 [3 4]
 [4 5]]


In [2]:
# indexing and slicing in numpy
import numpy as np
var = np.array([[1,2],[1,4]])
print(var[0][1])

2


In [5]:
var1 = ([1,2,3,4,5,6,7,8,9])
print(var1[1:8])


[2, 3, 4, 5, 6, 7, 8]


In [7]:
var2 = ([2,4,6,8,10,12,14])
print(var2[:6])


[2, 4, 6, 8, 10, 12]


In [12]:
# slicing in numpy
var4 = np.array([[1,2,3,4,5],[2,4,5,6,7],[3,6,9,12,15]])
print(var4[1,1:])


[4 5 6 7]


In [20]:
# iteration in numpy
var1 = np.array([1,2,4,5,6])
for i in var1:
    print(i)


1
2
4
5
6


In [24]:
var2 = np.array([[1,2,3,4,5],[1,3,5,7,9]])
for i in var2:
    for j in i:
        print(j)

1
2
3
4
5
1
3
5
7
9


In [26]:
var3 = np.array([[[1,3,5,7,9], [2,3,5,6,7], [2,4,6,8,10]]])
for i in var3:
    for j in i:
        for k in j:
            print(k)

1
3
5
7
9
2
3
5
6
7
2
4
6
8
10


In [29]:
var4 = np.array([[[1,2,3,4,5], [1,4,5,7,8], [2,4,6,8,9]]])
print(np.nditer(var4))
for i in np.nditer(var4):
    print(i)

1
2
3
4
5
1
4
5
7
8
2
4
6
8
9


In [32]:
var5 = ([[[2,3,4,5,6],[1,2,3,4,5], [1,3,5,7,9]]])
for i in np.nditer(var5):
    print(i)

2
3
4
5
6
1
2
3
4
5
1
3
5
7
9


In [44]:
var5 = ([[[2,3,4,5,6],[1,2,3,4,5], [1,3,5,7,9]]])
for i in np.ndenumerate(var5):
    print(i)

((0, 0, 0), np.int64(2))
((0, 0, 1), np.int64(3))
((0, 0, 2), np.int64(4))
((0, 0, 3), np.int64(5))
((0, 0, 4), np.int64(6))
((0, 1, 0), np.int64(1))
((0, 1, 1), np.int64(2))
((0, 1, 2), np.int64(3))
((0, 1, 3), np.int64(4))
((0, 1, 4), np.int64(5))
((0, 2, 0), np.int64(1))
((0, 2, 1), np.int64(3))
((0, 2, 2), np.int64(5))
((0, 2, 3), np.int64(7))
((0, 2, 4), np.int64(9))


In [41]:
# copy vs view in numpy

var = np.array([1,2,3,4,5])
co = var.copy()
var[1] = 24
print(co)
print(var)

[1 2 3 4 5]
[ 1 24  3  4  5]


In [1]:
import numpy as np
var1 = np.array([2,4,6,8,10])
vi = var1.view()
var1[2] = 45
print(vi)
print(var1)

[ 2  4 45  8 10]
[ 2  4 45  8 10]


In [4]:
# joiniing and spliting in numpy
# join array
var = np.array([1,2,3,4,5])
var1 = np.array([1,4,6,9,0])

x = np.concatenate((var,var1))
print(x)


[1 2 3 4 5 1 4 6 9 0]


In [10]:
var = np.array([[1,2], [3,4]])
var1 = np.array([[1,4], [6,9]])
x1 = np.concatenate((var,var1), axis=0)
print(x1)


[[1 2]
 [3 4]
 [1 4]
 [6 9]]


In [15]:
var1 = np.array([1,5,7,9])
var2 = np.array([1,2,3,4])
x2 = np.dstack((var1,var2))
print(x2)

[[[1 1]
  [5 2]
  [7 3]
  [9 4]]]


In [18]:
# split arrays
a = np.array([1,3,5,7,8,9])
b = np.array_split(a,3)
print(b)

[array([1, 3]), array([5, 7]), array([8, 9])]


In [20]:
# fucntions in numpy

# where function

var = np.array([1,3,5,6,8])
vr = np.where(var == 5)
print(vr)

(array([2]),)


In [23]:
# seacrhsorted

var1 = np.array([2,4,6,8,9,10,11,12,15])
vr1 = np.searchsorted(var1, [5,7])
print(vr1)

[2 3]


In [38]:
# sort 
var2 = np.array([1,99,34,2,4,67,5,6,96,100,12])
print(np.sort(var2))

[  1   2   4   5   6  12  34  67  96  99 100]


In [39]:
# filter

var_3 = np.array([2,4,6,8,9,10])
f = (True,False,False,True,False,True)
t_a = var_3[f]
print(t_a)


[]


In [40]:
var_4 = np.array(["a","b","c","d"])
f = (True,False,False,True)
z_a = var_4[f]
print(z_a)

[]


In [3]:
import numpy as np

var5 = np.array(["B", "C", "A", "D"])
print(np.sort(var5))

['A' 'B' 'C' 'D']


In [7]:
var = np.array([1,2,3,4,5,6])

np.random.shuffle(var)
print(var)


[1 4 3 5 6 2]


In [13]:
var1 = ([2,1,2,1,2,4,5,6,7,8])
x = np.unique(var1)
print(x)

[1 2 4 5 6 7 8]


In [16]:
var2 = ([1,2,3,4,5,6])
x = np.resize(var2,(2,3))
print(x)

[[1 2 3]
 [4 5 6]]


In [27]:
# matrix in numpy

var = np.matrix([[1,2], [2,3]])
var1 = np.matrix([[1,2], [2,3]])
print()
print(var.dot(var1))
print(var)



[[ 5  8]
 [ 8 13]]
[[1 2]
 [2 3]]


In [30]:
var3 = np.matrix([[1,2,3],[4,5,6]])
print(np.transpose(var3))
print(var3)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
